---
title: "Bioinformatics servers: User policy "
author:  "WCB Bioinformatics Core Facility"
output:
  html_document:
    fig_width: 1
    toc: true
    toc_depth: 2
---

------------------------------------------------------------------------

## Servers

These servers are fully paid for by the Wellcome Trust Centre for Cell Biology and are managed by the bioinformatics core facility.

Servers can be accessed by users who are logged in to the University VPN service.

-   bifx-core2.bio.ed.ac.uk (coming soon)

-   bifx-core3.bio.ed.ac.uk

    -   Command line usage (ssh)

    -   R-Studio: <https://bifx-rstudio.bio.ed.ac.uk/>

    -   R-Shiny: <http://bifx-core3.bio.ed.ac.uk:3838/>

    -   Apache web server

## Data policy

-   No personal data should be stored on the bifx-\* servers. All data should be related to projects associated with the Wellcome Centre unless dispensation has been given by the centre director.

-   All data on the bifx-\* servers can be viewed by members of the bioinformatics core or the centre director.

-   As the bioinformatics core group has superuser permissions, we can see all data on the server. Instructions on how to access the servers are lodged with the centre director in case of emergency. Therefore they are a de-facto administrator.

-   Your data can be accessed by your PI on request. No request is needed if the PI has an account on the server and can view your files. The data stored on the servers should only relate to the Wellcome Centre PI grant holder for the projects and therefore it is reasonable that they can access their own data.

-   Users are responsible for their own data (see backup policy).

-   By default, when you create a new file on the server it is created with the following permissions:

    -   Personal: read/write/execute
    -   Global/group: read

-   This means that only you can change, delete or execute the new file, but anyone logged in to the server can view it. If you would like to change the permissions on a file you can use the `chmod` command. Further details on how to do this can be found by reviewing our introduction to linux course.

## Data management

-   Users should have a data management plan for their projects. Please see [this document](https://uoe.sharepoint.com/:w:/s/wcbbioinformatics/EQAVC1KoHmtBrA6rUOasQcIBisBh2fIQ3gBp7XA_3zWlxQ?e=c2xMbY) for advice.

-   Users should endeavour to minimise disk usage by removing unnecessary files and compressing files where appropriate.

-   Completed projects should be archived with metadata and code to ensure reproducibility.

-   Before you leave the university, please ensure all required data is accessible to your group.

-   Group folders exist on the bifx servers at /groups. These can be used for shared data and for archiving old projects/accounts.

-   Please follow our recommended [best practices](best_practices.html) for working on the bifx servers. This web page will be updated semi-regularly.

## Server usage

-   All users must complete our [introduction to linux](http://bifx-core3.bio.ed.ac.uk/hyweldd/training/Bioinformatics_on_the_Command_Line/) course, either in their own time or by attending one of our workshops.

-   The bioinformatics servers are a shared environment and users are responsible for ensuring their jobs do not overwhelm computing resources. The servers can cope with high memory usage and multi-threading, however they will slow down when there is a high number of read/write operations.

    -   Limit simultaneous jobs with large read/write requirements (e.g. genome alignment).

    -   Do not set multi-threaded jobs to use the majority of CPUs.

-   In particular, users should be aware of Unix commands to monitor their jobs and avoid overuse of computing resources, e.g:

    -   `ps / pgrep`
    -   `top / htop`
    -   `nice`
    -   `kill`

-   Use the scratch space in `/scratch` to speed up analyses/downloads/uploads. This is local disk space which will respond quicker. However, it is **NOT BACKED UP** and should be used as temporary storage only. All key datasets should be transferred to your home space.

## Software and updates

-   The core facility will regularly maintain software and updates. We will strive to provide adequate warning when updates may cause interruption. All communication will be broadcast via the bifx-users mailing list (see below).

-   Details on version control of bioinformatics software and maintaining your own packages are available in our [best practices](best_practices.html) section.

## Storage and Backups

-   Data saved in home directories is stored on the University of Edinburgh DataStore service. Two backup systems exist:

    -   Daily 'snapshots' kept for two weeks to allow users to restore data.

    -   Daily tape backups kept for sixty days in case of total data loss.

-   Data in `/scratch` directories is not backed up. This disk space is provided to speed up analysis but output files should be copied back to your home directory. Please remove data from /scratch regularly to free up space for other users. Old data may be periodically removed by the bioinformatics core facility to free up space.

-   We recommend that users keep additional backups of key datasets e.g:

    -   Personal copies on encrypted external HDD.

    -   Online research data repositories e.g.

        -   Sequence repositories (GEO, SRA, ArrayExpress)

        -   [Zenodo](https://zenodo.org/)

-   See [here](https://www.ed.ac.uk/infosec/how-to-protect/encrypting) for university advice on encrypting devices.

## Mailing list

To join our mailing list, please send an email with no subject line to the following address: [sympa\@mlist.is.ed.ac.uk](mailto:sympa@mlist.is.ed.ac.uk){.email}

Include the following 2 lines of text (replacing FIRSTNAME and LASTNAME with your own first name and surname) SUBSCRIBE [bifx-users\@mlist.is.ed.ac.uk](mailto:bifx-users@mlist.is.ed.ac.uk){.email} FIRSTNAME LASTNAME QUIT
